module.exports = ["Leonardo Da Vinci’s Salvator Mundi",
                  "Les Femmes d’Alger",
                  "The Gigayacht ",
                  "Giacometti’s Pointing Man",
                  "Rabbit by Jeff Koons",
                  "Portrait of an Artist",
                  "Oppenheimer Blue Diamond",
                  "1962 Ferrari 250 GTO Berlinetta",
                  "Jimson Weed/White Flower No. 1 by Georgia O’Keeffe",
                  "Badminton Cabinet",
                  "Marie Antoinette’s Pendant",
                  "The Clark Sickle Leaf Carpet",
                  "Leonardo Da Vinci’s Codex Leicester - $30 million",
                  "Roman Era Statue of Artemis and the Stag",
                  "Fauteuil Aux Dragons by Eileen Gray"];